// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybgCguuLlYkJxIMRmEa1lZv8UWK-KO2k',
    appId: '1:605083479990:ios:0d74af60c38b9602e31b17',
    messagingSenderId: '605083479990',
    projectId: 'farm-lancer',
    storageBucket: 'farm-lancer.appspot.com',
    androidClientId: '605083479990-61nm8tkrhq69npe9k28tn6l78ik37vs2.apps.googleusercontent.com',
    iosClientId: '605083479990-dsrfgkihsksbvdjf33uvtl95jmlnf0r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmlancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybgCguuLlYkJxIMRmEa1lZv8UWK-KO2k',
    appId: '1:605083479990:ios:0d74af60c38b9602e31b17',
    messagingSenderId: '605083479990',
    projectId: 'farm-lancer',
    storageBucket: 'farm-lancer.appspot.com',
    androidClientId: '605083479990-61nm8tkrhq69npe9k28tn6l78ik37vs2.apps.googleusercontent.com',
    iosClientId: '605083479990-dsrfgkihsksbvdjf33uvtl95jmlnf0r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmlancer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWS6nuutzN5ihAKDq3KSewV7utzEYKniM',
    appId: '1:605083479990:web:0b7f7a361943f248e31b17',
    messagingSenderId: '605083479990',
    projectId: 'farm-lancer',
    authDomain: 'farm-lancer.firebaseapp.com',
    storageBucket: 'farm-lancer.appspot.com',
    measurementId: 'G-84SH621GD4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS6nuutzN5ihAKDq3KSewV7utzEYKniM',
    appId: '1:605083479990:web:0b7f7a361943f248e31b17',
    messagingSenderId: '605083479990',
    projectId: 'farm-lancer',
    authDomain: 'farm-lancer.firebaseapp.com',
    storageBucket: 'farm-lancer.appspot.com',
    measurementId: 'G-84SH621GD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6-FPW9vjDk2ayS_S3Q9F85zRv69274U',
    appId: '1:605083479990:android:89324f9f695fbd30e31b17',
    messagingSenderId: '605083479990',
    projectId: 'farm-lancer',
    storageBucket: 'farm-lancer.appspot.com',
  );

}